import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy';

import manifest from './manifest.json';

const isProd = (process.env.BUILD === 'production');

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const pluginPath = `obsidian-test-vault/.obsidian/plugins/${manifest.id}`

export default {
  input: 'main.ts',
  output: {
    dir: pluginPath,
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
    copy({
      targets: [
        {src: 'styles.css', dest: pluginPath},
        {src: 'manifest.json', dest: pluginPath}
      ]
    })
  ]
};